### ISSUE TITLE
Add error message if repo doesn't exist

### ISSUE THREAD

**Issue by ArthurCueio** [ArthurCueio/GitSize#1]
The github API returns nothing if the repo doesn't exist.

**Comment by badza** [comment]
Hello @ArthurCueio - the issue is fixed: https://github.com/badza/GitSize

**Comment by ArthurCueio** [comment]
Hi @badza submit your PR and I'll mege it soon. :tada:

**Comment by badza** [comment]
@ArthurCueio done
